apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "delivery-pulse.fullname" . }}
  labels:
    {{- include "delivery-pulse.labels" . | nindent 4 }}
data:
  ADO_ORG_URL: {{ .Values.config.adoOrgUrl | quote }}
  ADO_PROJECT: {{ .Values.config.adoProject | quote }}
  ADO_TEAMS: {{ .Values.config.adoTeams | quote }}
  SERVER_PORT: {{ .Values.server.containerPort | quote }}
