apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delivery-pulse.fullname" . }}
  labels:
    {{- include "delivery-pulse.labels" . | nindent 4 }}
type: Opaque
data:
  ado-client-secret: {{ .Values.secrets.adoClientSecret | b64enc | quote }}
