apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ado-reporter.fullname" . }}-backend
  labels:
    {{- include "ado-reporter.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "ado-reporter.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ado-reporter.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ include "ado-reporter.image" (dict "registry" .Values.imageRegistry "repository" .Values.backend.image.repository "tag" .Values.backend.image.tag) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "ado-reporter.fullname" . }}
          env:
            - name: ADO_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ado-reporter.fullname" . }}
                  key: ado-pat
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
