apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ado-reporter.fullname" . }}
  labels:
    {{- include "ado-reporter.labels" . | nindent 4 }}
type: Opaque
data:
  ado-pat: {{ .Values.secrets.adoPat | b64enc | quote }}
